config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :units do
    resources :comments
  end
  resources :instructors
  resources :courses
  
  resources :subscriptions
  resources :commitments
  root 'static_pages#home'
  resources :users


  post  'login', to: 'sessions#create'

  get   'dashboard/instructor', to: 'topics#instructor'
  get   'trending/topics', to: 'topics#trending'
  get   'profile', to: 'users#profile'
  get   'logout', to: 'sessions#destroy'
  get   'contact', to: 'static_pages#contact', as: 'contact'
  get   'dashboard', to: 'subscriptions#index', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
	has_many :courses

	has_secure_password
	validates 	:password, presence: { message:'Password is missing' }, length: { minimum: 6, message: 'Your password must be at least 6 char long'}, allow_nil: true
	validates_confirmation_of :password
	validates :email, presence: true
	validates :name, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    if @instructor.save
      log_in @instructor
      flash[:success] = 'Register successfully completed'
      redirect_to dashboard_instructor_path
    else
      flash[:errors] = @instructor.errors
      redirect_to request.referer
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :email, :password, :phone)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :instructor_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :instructor_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :instructor_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<div class="margin-top_angel">
  <div class="container">


    <div class="row">
      <p id="notice"><%= notice %></p>

      <div class="col-md-12">


        <div class="panel panel-default">
        <% @instructors.each do |instructor| %>
        <div class="col-md-4">

          <div id="container">
            <div class="image" style="background-image: url(https://25.media.tumblr.com/f9cd81645ebd2f0904227b42784bbfae/tumblr_mj6r7nBfdV1s7aky5o2_r1_1280.jpg)"></div>
            <div class="info">

              <h1 class="position">
              <%= link_to instructor.name, instructor_path(instructor) %>
            </h1>
            <h4><i class="fa fa-map-marker"></i> India (Punjab)</h4>
            <p><i class="fa fa-briefcase"></i> Web Design and Development.</p>
              <div class="social">
                <a href=""><i class="fa fa-twitter fa-2x"></i></a>
                <a href=""><i class="fa fa-linkedin fa-2x"></i></a>
                <a href=""><i class="fa fa-facebook-square fa-2x"></i></a>
                <a href=""><i class="fa fa-google-plus fa-2x"></i></a>
                <a href=""><i class="fa fa-github fa-2x"></i></a>
                <a href=""><i class="fa fa-youtube fa-2x"></i></a>
              </div>
            </div>
          </div>

    </div>
    <% end %>
  </div>

</div>
</div>
</div>
</div>
</div>
</div>
<br>

<div class="col-md-8">
<%= link_to 'New Instructor', new_instructor_path %>
</div>

app/views/instructors/new.html.erb
<!-- <h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %> -->








<section class="first-section">
	<div class="responsive-division hidden visible-xs"></div>
	
	    <div class="login-signup">
	      <div class="row">
	        <div class="col-sm-6 nav-tab-holder">
	        <ul class="nav nav-tabs row" role="tablist">
	          <li role="presentation" class="active col-sm-6"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Learner</a></li>
	          <li role="presentation" class="col-sm-6"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Instructor</a></li>
	        </ul>
	      </div>

	      </div>


	      <div class="tab-content">
	        <div role="tabpanel" class="tab-pane active" id="home">
	          <div class="row">
	            <div class="col-md-12 mobile-pull">
	              <article role="login">
	                <h3 class="text-center"><i class="fa fa-lock"></i>Create a learner account</h3>
	                <%= form_for(:user, url: users_path, html: { :multipart => true }) do |form| %>
	                <form class="signup" action="index.html" method="post">
	                  <div class="form-group">
	                    <%= form.text_field :email, id: :user_name, class:'form-control', placeholder: 'Email Address' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.text_field :name, id: :name, class:'form-control', placeholder: 'Name and last name' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password, id: :password, class:'form-control', placeholder: 'Password' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password_confirmation, id: :password_confirmation, class:'form-control', placeholder: 'Password Confirmation' %>
	                  </div>
	                 <!--  <div class="form-group">
	                    <%= form.file_field :picture %>
	                  </div> -->
	                  <div class="form-group">
	                    <div class="checkbox">
	                      <label>
	                        <input type="checkbox"> Please accept the terms and conditions to proceed with your request.
	                      </label>
	                    </div>
	                  </div>
	                  <div class="form-group">
	                    <%= form.submit 'SUBMIT', class: 'btn-success-register btn-block'%>
	                  </div>
	                <% end %>


	              </article>
	            </div>


	          </div>
	          <!-- end of row -->
	        </div>

	      <div role="tabpanel" class="tab-pane" id="profile">
	        <div class="row">

	          <div class="col-md-12 mobile-pull">
	            <article role="login">
	              <h3 class="text-center"><i class="fa fa-lock"></i> Become an instructor today</h3>
	              <%= form_for(:instructor, url: instructors_path) do |form| %>
	                <form class="signup" action="index.html" method="post">
	                  <div class="form-group">
	                    <%= form.text_field :email, id: :user_name, class:'form-control', placeholder: 'Email Address' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.text_field :name, id: :name, class:'form-control', placeholder: 'Name and last name' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password, id: :password, class:'form-control', placeholder: 'Password' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password_confirmation, id: :password_confirmation, class:'form-control', placeholder: 'Password Confirmation' %>
	                  </div>
	                  <div class="form-group">
	                    <div class="checkbox">
	                      <label>
	                        <input type="checkbox"> Please accept the terms and conditions to proceed with your request.
	                      </label>
	                    </div>
	                  </div>
	                  <div class="form-group">
	                    <%= form.submit 'SUBMIT', class: 'btn-success-register btn-block'%>
	                  </div>
	                <% end %>



	            </article>
	          </div>
	        </div>
	      </div>
	  </div>
	  </div>
	</div>
</section>
<% if flash[:errors] %>
<% errores = '' %>
<% flash[:errors].each do |err| %>
	<% errores << "<li>#{err}</li>".html_safe %>
<%end%>
<script>
  swal({
    html:true,
    title: "Opps...",
    text: '<ul><%= errores %></ul><img draggable="false" class="emoji" alt="😅" src="https://s.w.org/images/core/emoji/2.3/svg/1f605.svg" style="max-width: 20%;">'
  });
</script>
<% end %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>
<section class="first-section">



  <div id="mainwrap">


        <h1><%= @instructor.name %></h1>
        <h2>Web Developer from Medford</h2>
        <ul id="menu">
          <li><a class="profile" href="#profile" title="Profile">Profile</a><span>Some information about me</span></li>
          <li><a class="resume" href="#resume" title="Resume">Resume</a><span>Professional information</span></li>

          <li><a class="contact" href="#contact" title="Contact">Contact</a><span>Get in touch</span></li>
        </ul>

      <div style="clear:both"></div>
      <div id="content">
        <div id="profile" class="section">
          <div class="column col3">
            <table id="bioinfo">
              <tbody>
                <tr>
                  <td class="odd">Name</td>
                  <td class="even"><%= @instructor.name %></td>
                </tr>
                <tr>
                  <td class="odd">Date of birth</td>
                  <td class="even">09.07.1999</td>
                </tr>
                <tr>
                  <td class="odd">Address</td>
                  <td class="even">Medford, MA</td>
                </tr>
                <tr>
                  <td class="odd">Languages</td>
                  <td class="even">English, French</td>
                </tr>
                <tr>
                  <td class="odd">Website</td>
                  <td class="even">mysite.com</td>
                </tr>
                <tr>
                  <td class="odd">Email</td>
                  <td class="even"><%= @instructor.email %></td>
                </tr>
              </tbody>
            </table>
            <ul class="social">
              <a href=""><i class="fa fa-twitter fa-2x"></i></a>
              <a href=""><i class="fa fa-linkedin fa-2x"></i></a>
              <a href=""><i class="fa fa-facebook-square fa-2x"></i></a>
              <a href=""><i class="fa fa-google-plus fa-2x"></i></a>
              <a href=""><i class="fa fa-github fa-2x"></i></a>
              <a href=""><i class="fa fa-youtube fa-2x"></i></a>
            </ul>
          </div>
          <div class="column col5 pl-50">
            <img src="http://img2.wikia.nocookie.net/__cb20100920201409/spongebob/images/a/a0/Sandy_Cheeks.svg" alt="Jane Medford" />
            <p>I am a web developer. I am also a squirrel that lives underwater? Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat</p>
          </div>
        </div>

        <div id="resume" class="section">
          <table id="cv">
            <tbody>
              <tr>
                <td class="col2"><div class="date">April 2012 - present</div></td>
                <td class="col6 pl-30">
                  <p class="company">LenixCode</p>
                  <p class="title">Senior Web Developer</p>
                  <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
                </td>
              </tr>
              <tr>
                <td class="col2"><div class="date">January 2011 - March 2012</span></td>
                <td class="col6 pl-30">
                  <p class="company">Bent&amp;Co</p>
                  <p class="title">Senior Web Developer</p>
                  <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
                </td>
              </tr>
              <tr>
                <td class="col2"><div class="date">June 2008 - December 2010</span></td>
                <td class="col6 pl-30">
                  <p class="company">PC World</p>
                  <p class="title">Junior Web Developer</p>
                  <p class="description">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat.</p>
                </td>
              </tr>
            </tbody>
          </table>

        </div>

        <div id="contact" class="section">
          <div class="column col3">
            <h3></h3>
            <p>Stockholm, Sweden</p>
            <p>Web: mysite.com<br />
              E-mail: <%= @instructor.email %></p>
          </div>
          <div class="column col5 pl-50">
            <h3>Send a message</h3>
            <form id="contactform">
              <p class="column col4"><label for="name">Name:</label><input type="text" name="name" id="name" /></p>
              <p class="column col4"><label for="email">E-mail:</label><input type="text" name="email" id="email" /></p>
              <p class="column col8"><label for="message">Message:</label><textarea rows="5" name="message" id="message"></textarea></p>
              <p class="column col8"><input class="button" type="button" value="Submit" /></p>
            </form>
          </div>
        </div>
      </div>


    </div>
  </body>

</div>
</div>
</section>
<%= link_to 'Back', instructors_path %>