config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :units do
    resources :comments
  end
  resources :instructors
  resources :courses
  
  resources :subscriptions
  resources :commitments
  root 'static_pages#home'
  resources :users


  post  'login', to: 'sessions#create'

  get   'dashboard/instructor', to: 'topics#instructor'
  get   'trending/topics', to: 'topics#trending'
  get   'profile', to: 'users#profile'
  get   'logout', to: 'sessions#destroy'
  get   'contact', to: 'static_pages#contact', as: 'contact'
  get   'dashboard', to: 'subscriptions#index', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :commitments
	has_many :subscriptions
	has_many :comments

	has_secure_password
	validates 	:password, presence: { message:'Password is missing' }, length: { minimum: 6, message: 'Your password must be at least 6 char long'}, allow_nil: true
	validates_confirmation_of :password
	validates :email, presence: true
	validates :name, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_login, only: [:new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def profile
    
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = 'Register successfully completed'
      redirect_to dashboard_path
    else
      flash[:errors] = @user.errors
      redirect_to request.referer
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

      if @user.update(user_params)
        flash[:success] = 'Profile updated'
        redirect_to request.referer
      else
        flash[:success] = @user.errors
        redirect_to request.referer
      end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_login
      redirect_to dashboard_path if current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :phone, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<<<<<<< HEAD
<!-- <p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
 -->

 <!-- Navigation -->
 <a href="#top" id="back-to-top">
   <i class="fa fa-angle-double-up" aria-hidden="true">
   </i>
 </a>

    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                  <span class="glyphicon glyphicon-fire"></span>
                  LOGO
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Login</a>
                    </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Services <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="about-us">
              <li><a href="#">Top Commitments</a></li>
              <li><a href="#">Find Courses</a></li>
              <li><a href="#">Create Course</a></li>
            </ul>
          </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

  <!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
              <img src="../images/white.png" alt="logo">
              <p>The future of learning is here</p>
                <a href="#" class="btn btn-primary btn-lg">Engage Now</a>
            </div>
        </div>
    </header>

  <!-- Intro Section -->
    <section class="intro">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                  <span class="glyphicon glyphicon-fire" style="font-size: 60px"></span>
                    <h3 class="section-heading">Trending Courses</h3>
                </div>
            </div>
        </div>
        <div class="trending">
          <ul class="stats_box">
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>75k Commits</strong>Facial Recognition
                <span class="percent"> +16%</span>
              </div>
            </li>
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>165k Commits</strong>Artifical Neural Networks
                <span class="percent"> +23%</span>
              </div>
            </li>
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>17k Commits</strong>Bioinformatics
                <span class="percent"> +30%</span>
              </div>
            </li>
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>59K Commits</strong>HTML/CSS/JS/jQuery
                <span class="percent"> +10%</span>
              </div>
            </li>
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>75k Commits</strong>Facial Recognition
                <span class="percent"> +16%</span>
              </div>
            </li>
            <li>
              <div class="sparkline line_day">
                <canvas width="36" height="40" style="display: inline-block; width: 36px; height: 40px; vertical-align: top;"></canvas>
              </div>
              <div class="stat_text">
                <strong>165k Commits</strong>Artifical Neural Networks
                <span class="percent"> +23%</span>
              </div>
            </li>
          </ul>
        </div>
    </section>

  <!-- Content 1 -->
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="images/8.jpg" alt="">
                </div>
                <div class="col-sm-6">
                  <h2 class="section-header">Courses</h2>
                  <p class="lead text-muted">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                  <a href="#" class="btn btn-primary btn-lg">Classify It</a>
                </div>

            </div>
        </div>
    </section>

  <!-- Content 2 -->
     <section class="content content-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                  <h2 class="section-header">Superior Quality</h2>
                  <p class="lead text-light">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                  <a href="#" class="btn btn-default btn-lg">Test It</a>
                </div>
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="images/grid-AI.jpg" alt="">
                </div>

            </div>
        </div>
    </section>

    <!-- Promos -->
  <div class="container-fluid">
        <div class="row promo">
          <a href="#">
        <div class="col-md-4 promo-item item-1">
          <h3>
            Unleash
          </h3>
        </div>
            </a>
            <a href="#">
        <div class="col-md-4 promo-item item-2">
          <h3>
            Synergize
          </h3>
        </div>
            </a>

      <a href="#">
        <div class="col-md-4 promo-item item-3">
          <h3>
            Procrastinate
          </h3>
        </div>
            </a>
        </div>
    </div><!-- /.container-fluid -->

  <!-- Content 3 -->
     <section class="content content-3">
        <div class="container">
      <h2 class="section-header"><span class="glyphicon glyphicon-pushpin text-primary"></span><br> Sanity Check</h2>
      <p class="lead text-muted">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                    <a href="#" class="btn btn-primary btn-lg">Check Now</a>
            </div>
        </div>
    </section>

  <!-- Footer -->
    <footer class="page-footer">

      <!-- Contact Us -->
        <div class="contact">
          <div class="container">
        <h2 class="section-heading">Contact Us</h2>
        <p><span class="glyphicon glyphicon-earphone"></span><br> +1(23) 456 7890</p>
        <p><span class="glyphicon glyphicon-envelope"></span><br> info@example.com</p>
          </div>
        </div>

        <!-- Copyright etc -->
        <div class="small-print">
          <div class="container">
            <p>Copyright &copy; Example.com 2015</p>
          </div>
        </div>


    </footer>
=======
HERE SOMETHING WITH USERS
>>>>>>> cc107cb1a14e2ef571f1f14cfe066ec9fdbb7c22

app/views/users/new.html.erb
<section class="first-section">
	<div class="responsive-division hidden visible-xs"></div>
	<div class="container">
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

				<ul>
					<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
	    <div class="login-signup">
	      <div class="row">
	        <div class="col-sm-6 nav-tab-holder">
	        <ul class="nav nav-tabs row" role="tablist">
	          <li role="presentation" class="active col-sm-6"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Learner</a></li>
	          <li role="presentation" class="col-sm-6"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Instructor</a></li>
	        </ul>
	      </div>

	      </div>


	      <div class="tab-content">
	        <div role="tabpanel" class="tab-pane active" id="home">
	          <div class="row">
	            <div class="col-md-12 mobile-pull">
	              <article role="login">
	                <h3 class="text-center"><i class="fa fa-lock"></i>&ensp;Create a learner account</h3>
	                <%= form_for(:user, url: users_path, html: { :multipart => true }) do |form| %>
	                <form class="signup" action="index.html" method="post">
	                  <div class="form-group">
	                    <%= form.text_field :email, id: :user_name, class:'form-control', placeholder: 'Email Address' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.text_field :name, id: :name, class:'form-control', placeholder: 'Name and last name' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password, id: :password, class:'form-control', placeholder: 'Password' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password_confirmation, id: :password_confirmation, class:'form-control', placeholder: 'Password Confirmation' %>
	                  </div>
	                 <!--  <div class="form-group">
	                    <%= form.file_field :picture %>
	                  </div> -->
	                  <div class="form-group">
	                    <div class="checkbox">
	                      <label>
	                        <input type="checkbox"> Please accept the terms and conditions to proceed with your request.
	                      </label>
	                    </div>
	                  </div>
	                  <div class="form-group">
	                    <%= form.submit 'SUBMIT', class: 'btn-success-register btn-block'%>
	                  </div>
	                <% end %>


	              </article>
	            </div>


	          </div>
	          <!-- end of row -->
	        </div>

	      <div role="tabpanel" class="tab-pane" id="profile">
	        <div class="row">

	          <div class="col-md-12 mobile-pull">
	            <article role="login">
	              <h3 class="text-center"><i class="fa fa-lock"></i> Become an instructor today</h3>
	              <%= form_for(:instructor, url: instructors_path) do |form| %>
	                <form class="signup" action="index.html" method="post">
	                  <div class="form-group">
	                    <%= form.text_field :email, id: :user_name, class:'form-control', placeholder: 'Email Address' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.text_field :name, id: :name, class:'form-control', placeholder: 'Name and last name' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password, id: :password, class:'form-control', placeholder: 'Password' %>
	                  </div>
	                  <div class="form-group">
	                    <%= form.password_field :password_confirmation, id: :password_confirmation, class:'form-control', placeholder: 'Password Confirmation' %>
	                  </div>
	                  <div class="form-group">
	                    <div class="checkbox">
	                      <label>
	                        <input type="checkbox"> Please accept the terms and conditions to proceed with your request.
	                      </label>
	                    </div>
	                  </div>
	                  <div class="form-group">
	                    <%= form.submit 'SUBMIT', class: 'btn-success-register btn-block'%>
	                  </div>
	                <% end %>



	            </article>
	          </div>
	        </div>
	      </div>
	  </div>
	  </div>
	</div>
</section>
<%= render 'static_pages/partials/modal' %>
<% if flash[:errors] %>
<% errores = '' %>
<% flash[:errors].each do |err| %>
	<% errores << "<li>#{err}</li>".html_safe %>
<%end%>
<script>
  swal({
    html:true,
    title: "Opps...",
    text: '<ul><%= errores %></ul><img draggable="false" class="emoji" alt="😅" src="https://s.w.org/images/core/emoji/2.3/svg/1f605.svg" style="max-width: 20%;">'
  });
</script>
<% end %>

app/views/users/profile.html.erb
<section class="first-section">


  <div class="container">
    <div class="row">
        <div class="col-lg-5 col-md-12 col-sm-8 col-xs-9 bhoechie-tab-container">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 bhoechie-tab-menu">
              <ul class="list-group">
                <a href="#" class="list-group-item active">
                  <br/><i class="glyphicon glyphicon-user"></i> User<br/><br/>
                </a>
                <a href="#" class="list-group-item ">
                  <br/><i class="glyphicon glyphicon-tasks"></i> Subsciptions<br/><br/>
                </a>
                <a href="#" class="list-group-item ">
                  <br/><i class="glyphicon glyphicon-thumbs-up"></i> Commitments<br/><br/>
                </a>
                <a href="#" class="list-group-item">
                  <br/><h4 class="glyphicon glyphicon-wrench"></h4> Edit My Information<br/><br/>
                </a>
                <a href="#" class="list-group-item">
                  <br/><i class="glyphicon glyphicon-new-window"></i> New<br/><br/>
                  </a>
              </ul>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 bhoechie-tab">
                <!-- flight section -->
                <div class="bhoechie-tab-content active">
                    <%= form_for(:user, url: user_path(current_user), method:'PUT') do |f| %>
                      <center>
                        <%= image_tag current_user.avatar, class: 'img-responsive' %>
                        <h2 style="margin-top: 0;color:#00001a">Welcome</h2>
                        <h3 style="margin-top: 0;color:#00001a"><%= current_user.name %></h3>
                        <br/>
                        change pic:
                        <br/>
                        <%= f.file_field :avatar %>
                        <%= f.submit  %>
                      </center>
                    <% end %>
                </div>


                <div class="bhoechie-tab-content">
                    <center>
                      <h1 class="glyphicon glyphicon-tasks" style="font-size:12em;color:#00001a"></h1>
                      <h2 style="margin-top: 0;color:#00001a"><a href="/subscriptions" class="btn btn-sm btn-primary btn-block" role="button">Subscriptions</a></h2>
                      <h3 style="margin-top: 0;color:#00001a">My Subscriptions</h3>
                    </center>
                </div>


                <div class="bhoechie-tab-content">
                    <center>
                      <h1 class="glyphicon glyphicon-thumbs-up" style="font-size:12em;color:#00001a"></h1>
                      <h2 style="margin-top: 0;color:#00001a"><a href="/commitments" class="btn btn-sm btn-primary btn-block" role="button">Commits</a></h2>
                      <h3 style="margin-top: 0;color:#00001a">My Commitments </h3>
                    </center>
                </div>

                <div class="bhoechie-tab-content">
                    <center>
                      <h1 class="glyphicon glyphicon-edit" style="font-size:12em;color:#00001a"></h1>
                      <h2 style="margin-top: 0;color:#00001a">
                        <a href="" class="btn btn-sm btn-primary btn-block" role="button">Edit</a></h2>
                      <h3 style="margin-top: 0;color:#00001a">Settings</h3>
                    </center>
                </div>

                <div class="bhoechie-tab-content">
                    <center>
                      <h1 class="glyphicon glyphicon-flash" style="font-size:8em;color:#00001a"></h1>
                      <h2 style="margin-top: 0;color:#00001a"><a href="/courses" class="btn btn-sm btn-primary btn-block" role="button">Discover a new course</a></h2>
                      <h3 style="margin-top: 0;color:#00001a">Courses</h3>
                      <h1 class="glyphicon glyphicon-fire" style="font-size:8em;color:#00001a"></h1>
                      <h2 style="margin-top: 0;color:#00001a"><a href="/commitments" class="btn btn-sm btn-primary btn-block" role="button">Trending Commits</a></h2>
                      <h3 style="margin-top: 0;color:#00001a">Commit now!</h3>
                    </center>
                </div>
            </div>
        </div>
    </div>
  </div>
</section>
<% if flash[:success] %>
  <script>
    swal({
      html:true,
      title: "<%= flash[:success] %>",
      text: '<img draggable="false" class="emoji" alt="😀" src="https://s.w.org/images/core/emoji/2.3/svg/1f600.svg" style="max-width: 20%;">'
    });
  </script>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>