config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :units do
    resources :comments
  end
  resources :instructors
  resources :courses
  
  resources :subscriptions
  resources :commitments
  root 'static_pages#home'
  resources :users


  post  'login', to: 'sessions#create'

  get   'dashboard/instructor', to: 'topics#instructor'
  get   'trending/topics', to: 'topics#trending'
  get   'profile', to: 'users#profile'
  get   'logout', to: 'sessions#destroy'
  get   'contact', to: 'static_pages#contact', as: 'contact'
  get   'dashboard', to: 'subscriptions#index', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :comments
	belongs_to :course

	def minutes
		t = self.duration
		Time.at(t).utc.strftime("%H:%M")

	end




end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :duration, :embed_code)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :unit_name %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :unit_duration %>
  </div>

  <div class="field">
    <%= form.label :embed_code %>
    <%= form.text_area :embed_code, id: :unit_embed_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Embed code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.duration %></td>
        <td><%= unit.embed_code %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<section  class="first-section">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <p>
          <strong>
          <%= @unit.name %>
        </strong>
        </p>
        <p>
          <strong>Video Length:</strong>
          <%= @unit.minutes   %>
        </p>
      </div>
      <div class="col-md-9">
        <p id="notice"><%= notice %></p>
        <p>
          <%= @unit.embed_code.html_safe %>
          <%= social_share_button_tag(@unit.name) %>
        </p>
      </div>
      <div class="col-md-3">

        <div class="detailBox">
          <div class="titleBox">
            <label>Comment Box</label>
            <button type="button" class="close" aria-hidden="true">&times;</button>
          </div>
          <!-- <div class="commentBox">
            <% @unit.comments.each do |c| %>
              <span><%= c.comment %></span>
            <% end %>      
          </div> -->
          <div class="actionBox">
            <ul class="commentList">
              <% @unit.comments.order(id: :desc).each do |comment| %>
                <li>
                  <div class="commenterImage">

                    <%= image_tag(comment.user.avatar) %>
                  </div>
                  <div class="commentText">
                    <p class=""><%= comment.comment %></p> <span class="date sub-text"><span class="text-success"><%= comment.user.name %> </span>on <%= comment.created_at.strftime("%b %d, %y") %></span>
                  </div>
                </li>
              <%end%>
              
            </ul>

            <%= form_for(:comment, url: unit_comments_path(@unit), html: { class: 'form-inline'} ) do |f| %>

              <div class="form-group">
                <input class="form-control" name="comment[comment]" type="text" placeholder="Your comments" style="
    width: 235px;
" />

              </div>
              <div class="form-group">
                <%= f.submit 'ADD', class: 'btn btn-primary' %>
              </div>

            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% if flash[:success] %>
  <script>
    swal({
      html:true,
      title: "<%= flash[:success] %>",
      text: '<img draggable="false" class="emoji" alt="😀" src="https://s.w.org/images/core/emoji/2.3/svg/1f600.svg" style="max-width: 20%;">'
    });
  </script>
<% end %>