config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :units do
    resources :comments
  end
  resources :instructors
  resources :courses
  
  resources :subscriptions
  resources :commitments
  root 'static_pages#home'
  resources :users


  post  'login', to: 'sessions#create'

  get   'dashboard/instructor', to: 'topics#instructor'
  get   'trending/topics', to: 'topics#trending'
  get   'profile', to: 'users#profile'
  get   'logout', to: 'sessions#destroy'
  get   'contact', to: 'static_pages#contact', as: 'contact'
  get   'dashboard', to: 'subscriptions#index', as: 'dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :unit
	belongs_to :user
	validates :comment, presence: true
end

app/models/commitment.rb
class Commitment < ApplicationRecord
	belongs_to :user
	belongs_to :topic

	validates :price, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :instructor
	belongs_to :topic
	has_many :units
	has_many :subcriptions
end

app/models/instructor.rb
class Instructor < ApplicationRecord
	has_many :courses

	has_secure_password
	validates 	:password, presence: { message:'Password is missing' }, length: { minimum: 6, message: 'Your password must be at least 6 char long'}, allow_nil: true
	validates_confirmation_of :password
	validates :email, presence: true
	validates :name, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	belongs_to :course
end

app/models/topic.rb
class Topic < ApplicationRecord
	before_save :set_status

	has_many :courses
	has_many :commitments

	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
	validates :name, presence: true
	validates :cat, presence: true
	validates :language, presence: true
	validates :description, presence: true

	def set_status
		self.status = true
	end
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :comments
	belongs_to :course

	def minutes
		t = self.duration
		Time.at(t).utc.strftime("%H:%M")

	end




end

app/models/user.rb
class User < ApplicationRecord
	has_many :commitments
	has_many :subscriptions
	has_many :comments

	has_secure_password
	validates 	:password, presence: { message:'Password is missing' }, length: { minimum: 6, message: 'Your password must be at least 6 char long'}, allow_nil: true
	validates_confirmation_of :password
	validates :email, presence: true
	validates :name, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://www.1plusx.com/app/mu-plugins/all-in-one-seo-pack-pro/images/default-user-image.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :duration, :embed_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
	def get_total_time(course)
		course = course.units.map { |x| x.duration }
		course = course.reduce(0, :+)
		Time.at(course).utc.strftime("%H:%M:%S")
	end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id]    = user.id
      session[:instructor] = user.class.name == 'Instructor' ? true : false
  	end

  	def log_out
    	session.delete(:user_id)
    	@current_admin = nil
  	end

  	def current_user
    	@current_user ||= session[:instructor] ? Instructor.find_by(id: session[:user_id]) : User.find_by(id: session[:user_id])
   	end

   	def logged_in?
   		!current_user.nil?
    end

    def current_user?(user)
      user == current_user
    end

    def check_admin
      unless current_user.present? && current_user.roll == 'admin'
        redirect_to login_admin_path
      end
    end

    def check_buyer
      if !current_user.present?
        flash[:warning] = 'Debes iniciar sesion'
        redirect_to root_path
      end
    end

    def check_seller
      if !current_user.present? && current_user.roll != 'admin'
        redirect_to root_path
      end
    end

    def check_provider
      unless current_user.present? && current_user.roll == 'admin'
        redirect_to root_path
      end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
	def sum_topic(topic)
      prices    = topic.commitments.map { |x| x.price }
      prices.reduce(0, :+)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>BrinX</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="/css/custom.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/homepage.css">

    <link rel="shortcut icon" type="image/png" href="<%= image_url('favicon.ico') %>"/>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
  <body>
    <%= render 'layouts/partials/menu' %>
    <%= yield %>
    <%= render 'layouts/partials/footer' %>
  </body>
      <!-- jQuery -->

</html>

app/views/layouts/partials/_footer.html.erb
<!--   <footer class="page-footer">

        <div class="contact">
          <div class="container">
        <h2 class="section-heading">Contact Us</h2>
        <p><span class="glyphicon glyphicon-earphone"></span><br> +1(23) 456 7890</p>
        <p><span class="glyphicon glyphicon-envelope"></span><br> info@example.com</p>
          </div>
        </div>

        <div class="small-print">
          <div class="container">
            <p>Copyright &copy; Example.com 2015</p>
          </div>
        </div>

        <a href="#top" id="back-to-top">
    <i class="fa fa-angle-double-up" aria-hidden="true">
    </i>
  </a>

</footer>  -->




<footer class="page-footer">
   <div class="footer-bottom">
       <div class="container">
           <p class="pull-left"> ...let the students take control. </p>

           <div class="pull-right">
               <%= image_tag("logoandletterwhite.png" , class:"logo") %>

           </div>
       </div>
   </div>
</footer>

app/views/layouts/partials/_menu.html.erb
<!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand custom-logo" href="#">

                  <%= link_to image_tag('logoandletterwhite.png'), root_path %>
                </div>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                    <li>
                        <a href="/" >Home</a>
                    </li>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#myModal">Login</a>
                    </li>

                    <li class="<%=active_class('/contact')%>">
                      <%= link_to 'Contact', contact_path %>
                    </li>

                    <div class="dropdown">
                      <a href="" id="grid">
                        <i class="fa fa-th-large" aria-hidden="true"></i>
                      </a>

                      <div class="dropdown-content">
                        <a href="#"><i class="fa fa-code" aria-hidden="true"></i> Development</a>
                        <a href="#"><i class="fa fa-flask" aria-hidden="true"></i> Data Science</a>
                        <a href="#"><i class="fa fa-desktop" aria-hidden="true"></i> IT</a>
                        <a href="#"><i class="fa fa-line-chart" aria-hidden="true"></i> Analytics</a>
                        <a href="#"><i class="fa fa-paint-brush" aria-hidden="true"></i> Design</a>
                        <a href="#"><i class="fa fa-cloud" aria-hidden="true"></i> Software</a>
                        <a href="#"><i class="fa fa-cog" aria-hidden="true"></i> Hardware</a>
                      </div>
                    <!--   <button type="button" class="btn btn-primary" >
                          Launch demo modal
                        </button> -->

                    </div>
                    <li class="<%=active_class('/course')%>">
                        <%= link_to 'Courses', courses_path %>
                    </li>

                <% else %>
                    <li class="<%=active_class('/course')%>">
                        <%= link_to '<i class="fa fa-dashboard" ></i>&ensp;Dashboard'.html_safe, dashboard_path %>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <%=current_user.name%>&nbsp;
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            <%= image_tag current_user.avatar, class:'img-responsive'%>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong><%=current_user.name%></strong></p>
                                        <p class="text-left small"><%=current_user.email%></p>
                                        <p class="text-left">
                                            <%= link_to 'Update profile', profile_path, class: 'btn btn-warning btn-block btn-sm' %>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                            <%= link_to 'Logout', logout_path, class: "btn btn-danger btn-block" %>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>



                <% end %>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

<!-- Header -->

app/views/layouts/partials/_user_menu.html.erb
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-thumbs-up">
          </span>&ensp;Topics</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <ul class="list-group">
        <li class="list-group-item"><span class="glyphicon glyphicon-plus text-success"></span>

          <%= link_to '&ensp;&ensp;Create a new topic'.html_safe, new_topic_path %>
        </li>

        <li class="list-group-item"><span class="glyphicon glyphicon-flash text-success"></span>

          <%= link_to '&ensp;&ensp;All topics'.html_safe, topics_path %>
        </li>
        <li class="list-group-item">
          <%= link_to '<i class="fa fa-rocket text-success"></i>&ensp;&ensp;&ensp;Trending topics'.html_safe, trending_topics_path %>
        </li>
      </ul>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a href="/courses"><i class="fa fa-list" ></i>&ensp;Courses</a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a href="/dashboard"><i class="fa fa-tv" ></i>&ensp;My subscriptions</a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class=" glyphicon glyphicon-envelope">
          </span>&ensp;Messages</a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="list-group">

        <a href="#" class="list-group-item">Direct messages</a>
        <a href="#" class="list-group-item">Unit discusions</a>
        <a href="#" class="list-group-item">Course discusions</a>

      </div>
    </div>
  </div>
  
</div>